server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:/Users/User/Desktop/native-file-repo
        git:
#          uri: C:/Users/User/Desktop/git-local-repo
          uri: https://github.com/AE-OO/study_MSA_springCloudConfig
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
