server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: C:/Users/User/Desktop/git-local-repo
          uri: https://github.com/AE-OO/study_MSA_springCloudConfig
          default-label: master
