server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/native-file-repo
        git:
#          uri: C:/Users/User/Desktop/git-local-repo
          uri: https://github.com/AE-OO/study_MSA_springCloudConfig
          default-label: master
